### ISSUE TITLE
 [MacOS-Chrome-1920px-로그인] 접속시 비밀번호 인풋에 대한 helper-text 노출

### ISSUE THREAD

**Issue by gmlwlsdl** [100-hours-a-week/2-danny-oh-community-issue#45]
**버그 설명**
단순히 로그인 페이지에 접속하기만 해도 비밀번호 input에 대한 hyper-text가 노출되고 있습니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 로그인 페이지에 접속한다.

**예상한 동작**
1. 로그인 페이지에 접속한다.
2. 이메일 or 비밀번호 필드에 값을 입력한다.
3. **유효성 검사를 만족하지 않을시** helper-text를 보인다.

**스크린샷**
![image](https://github.com/user-attachments/assets/b98701c9-68c8-40dc-ab36-967f1839883b)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: MacOs
 - Browser: Chrome
 - Version: 131.0.6778.109(arm64)

**추가적인 내용:**
필드에 값을 입력하지 않아도 기본으로 띄우는 것이 의도된 플로우일까요?? 👀

**Comment by happy-yeachan** [comment]
수정 완료했습니당
